# Generated by Django 5.0.6 on 2024-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.TextField(default=None, null=True, verbose_name='Отчёт'),
        ),
    ]
